version: '3'

services:
  nginx:
    depends_on:
      - vote
    image: opsani/sample-lb:1.0
    labels:
      io.skopos.dt.vote: _
      io.skopos.glc.pre_flight.0: plugin docker network_create
      io.skopos.glc.pre_flight.0.ext: ',l=Ensure project network exists'
      io.skopos.lb.name: in
      io.skopos.lb.position: 20,150
      io.skopos.lc.quality_probe.0: probe opsani/probe-http service_up n=&l=&t=
      io.skopos.lc.quality_probe.0.ext: ',l=Verify nginx: http probe service_up port 80'
      io.skopos.singleton: '1'
      io.skopos.visual.position: 300,150
    ports:
      - ${http_port_docker-8080}:80

  vote:
    depends_on:
      - back
    deploy:
      replicas: 3
    expose:
      - '80'
    image: opsani/sample-front:${front_ver:-1.1}
    labels:
      io.skopos.dt.back: _
      io.skopos.lc.post_instance_attach.0: plugin docker comp_signal {"signal":"HUP","target":"nginx"}
      io.skopos.lc.post_instance_detach.0: plugin docker comp_signal {"signal":"HUP","target":"nginx"}
      io.skopos.lc.quality_probe.0: probe opsani/probe-http service_up n=&l=&t=
      io.skopos.lc.quality_probe.0.ext: ',l=Verify vote: http probe service_up port 80'
      io.skopos.visual.position: 600,150

  back:
    deploy:
      replicas: 3
    expose:
      - '8080'
    image: opsani/sample-back:${back_ver:-1.0}
    labels:
      io.skopos.lc.quality_probe.0: probe opsani/probe-http service_up n=&l=&t= {"port":"8080"}
      io.skopos.lc.quality_probe.0.ext: ',l=Verify back: http probe service_up port 8080'
      io.skopos.visual.position: 900,150
